# -*- coding: utf-8 -*-
"""source-code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0bFifPmGUp92ZvD7SOCQamKCG0R17ii
"""

from google.colab import files
uploaded = files.upload()

!pip install xgboost

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    recall_score,
    precision_score,
    confusion_matrix,
    classification_report
)

from xgboost import XGBClassifier

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

print(train.shape)
print(test.shape)

train.head()

X = train.drop(["Y", "CoilID"], axis=1)
y = train["Y"]

X_test = test.drop(["CoilID"], axis=1)

print(X.shape)
print(y.shape)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print(X_train.shape)
print(X_val.shape)

print(y.value_counts())
print()
print(y.value_counts(normalize=True))

negative = 1286
positive = 66

scale_pos_weight = negative / positive

print(scale_pos_weight)

model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    scale_pos_weight=19.48,
    random_state=42
)

model.fit(X_train, y_train)

probs = model.predict_proba(X_val)[:, 1]

print(probs[:10])

best_threshold = 0
best_precision = 0

for t in [i/100 for i in range(1,100)]:

    preds = (probs >= t).astype(int)

    recall = recall_score(y_val, preds)
    precision = precision_score(y_val, preds, zero_division=0)

    if recall == 1.0:
        print(f"Threshold: {t:.2f}")
        print(f"Recall: {recall:.2f}")
        print(f"Precision: {precision:.2f}")
        print("-------------------")

        if precision > best_precision:
            best_precision = precision
            best_threshold = t

print("Best Threshold:", best_threshold)
print("Best Precision:", best_precision)

threshold = 0.01

preds = (probs >= threshold).astype(int)

print("Recall:", recall_score(y_val, preds))
print("Precision:", precision_score(y_val, preds))
print()

print(confusion_matrix(y_val, preds))

model = XGBClassifier(
    n_estimators=1000,
    max_depth=8,
    learning_rate=0.03,
    scale_pos_weight=30,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

model.fit(X_train, y_train)

probs = model.predict_proba(X_val)[:, 1]

print(probs[:10])

for t in [0.001, 0.003, 0.005, 0.01, 0.02, 0.03, 0.05]:

    preds = (probs >= t).astype(int)

    recall = recall_score(y_val, preds)
    precision = precision_score(y_val, preds, zero_division=0)

    print(f"Threshold = {t}")
    print("Recall =", recall)
    print("Precision =", precision)
    print(confusion_matrix(y_val, preds))
    print("-------------------")

!pip install imbalanced-learn

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)
X_test_imputed = imputer.transform(X_test)

print(X_train_imputed.shape)

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train_imputed,
    y_train
)

print(X_train_smote.shape)
print(y_train_smote.value_counts())

model = XGBClassifier(
    n_estimators=1200,
    max_depth=8,
    learning_rate=0.03,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

model.fit(X_train_smote, y_train_smote)

probs = model.predict_proba(X_val_imputed)[:, 1]

for t in [0.001, 0.003, 0.005, 0.01, 0.02, 0.03, 0.05]:

    preds = (probs >= t).astype(int)

    recall = recall_score(y_val, preds)
    precision = precision_score(y_val, preds, zero_division=0)

    print(f"Threshold = {t}")
    print("Recall =", recall)
    print("Precision =", precision)
    print(confusion_matrix(y_val, preds))
    print("-------------------")

test_probs = model.predict_proba(X_test_imputed)[:, 1]

threshold = 0.001

test_preds = (test_probs >= threshold).astype(int)

print(test_preds[:20])

submission = pd.DataFrame({
    "CoilID": test["CoilID"],
    "Y": test_preds
})

submission.head()

submission.to_csv("expected_submission.csv", index=False)

print("Submission file created successfully!")

from google.colab import files

files.download("expected_submission.csv")